// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1F_G5L88G2P0C8wJyJGKBB-RNAwitqx8',
    appId: '1:370303622091:android:02df0cf2cbcfc3847ff44e',
    messagingSenderId: '370303622091',
    projectId: 'productosmercado-e2afb',
    databaseURL: 'https://productosmercado-e2afb-default-rtdb.firebaseio.com',
    storageBucket: 'productosmercado-e2afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNHArDfyaVpiAsG91sePAvLUIM0cccMoo',
    appId: '1:370303622091:ios:2ac2a20894acf06f7ff44e',
    messagingSenderId: '370303622091',
    projectId: 'productosmercado-e2afb',
    databaseURL: 'https://productosmercado-e2afb-default-rtdb.firebaseio.com',
    storageBucket: 'productosmercado-e2afb.appspot.com',
    iosBundleId: 'com.example.trabajofinal',
  );
}
